### ISSUE TITLE
Bullet should be removed after hit

### ISSUE THREAD

**Issue by CarmenIJsebaart** [richelbilderbeek/AminoAcidFighter#15]

**Comment by richelbilderbeek** [comment]
Just want to have it mentioned: I do enjoy the current behavior :sunrise: :sunrise_over_mountains: :city_sunrise: 

Feel free to ignore :stuck_out_tongue_winking_eye:

**Comment by CarmenIJsebaart** [comment]
I will take it into account :dancing_women:

**Comment by CarmenIJsebaart** [comment]
Bullet is now removed if the speed is too low

**Comment by CarmenIJsebaart** [comment]
Done! Bullet slows even more down when hitting a player!
