### ISSUE TITLE
Fix memory leak!

### ISSUE THREAD

**Issue by CarmenIJsebaart** [richelbilderbeek/AminoAcidFighter#18]

**Comment by CarmenIJsebaart** [comment]
I already removed the sprite pointers

**Comment by richelbilderbeek** [comment]
Added `memcheck` to see if there still is a memory leak (which I doubt).

**Comment by richelbilderbeek** [comment]
It looks like we're clean:

![aminoacidfighterleaks](https://cloud.githubusercontent.com/assets/2098230/26780334/9b23693e-49e9-11e7-8841-69d735f5bccb.png)

Closing this Issue due to this.
