### ISSUE TITLE
Create special moves of AminoAcids

### ISSUE THREAD

**Issue by CarmenIJsebaart** [richelbilderbeek/AminoAcidFighter#5]

**Comment by JorikdeBoer** [comment]
Special moves for 20 amino acids:

                1. Freeze & anti Freeze all players
		2. Reverse speed (speed_x becomes -speed_x) & back again
		3. Mix speed (speed_x becomes speed_y, vice versa) & back again 
		4. Reversed controls (left becomes right, right becomes left) & back again
		5. strafe left 
		6. strafe right
		7. temporary shield
		8. shoot from opposite side
		9. turbo boost, extra speed
		10. slowdown & speed up own aminoacid
		11. single homing missele to lock on 1 other player
		12. a few power_shots, more powerful shots
		13. Kamikaze, everybody gets hit
		14. Freeze & anti Freeze own aminoacid
		15. minimize for certain time
		16. maximize for certain time
		17. switch players
		18. crash, bumping hurts other players
		19. temporary invisibility
		20. temporary invulnerable
