### ISSUE TITLE
Add joystick support

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/AminoAcidFighter#9]
Richel will lend two XBox 360 controllers.

**Comment by CarmenIJsebaart** [comment]
It is now possible to use the controllers to play with player three and four, but navigating is still impossible (speed is magnificent, haha)!

**Comment by richelbilderbeek** [comment]
I see keyboard handling is described [in the SFML docs](http://www.sfml-dev.org/documentation/2.0/classsf_1_1Keyboard.php#details) and I did exactly what is recommended not to do (that is, store key state)

**Comment by CarmenIJsebaart** [comment]
I put the keyboard input back to "normal"! :)

**Comment by richelbilderbeek** [comment]
AFAIK this has been done.
